vim.o.number = true
vim.o.relativenumber = true
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.termguicolors = true
vim.o.smartindent = true
vim.o.background = "dark"
vim.g.mapleader = " "
vim.g.maplocalleader = " "
